server:
  port: ${PORT:8080}

spring:
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:linko-training}
      storage:
        bucket: ${GCS_BUCKET:linko-challenge-files}

storage:
  gcs:
    prefix: ${GCS_PREFIX:mid-uploads/}

cloud-run:
  base-url: https://linko-java-api-mid-430799291004.us-central1.run.app
  audience: https://linko-java-api-mid-430799291004.us-central1.run.app
  remote-api:
    enabled: ${CLOUD_RUN_REMOTE_API:false}
